server:
  port: 8080
project:
  auther: czh
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Springboot_Vue?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: biefanglajiao
    password: 020116zh
    driver-class-name: com.mysql.cj.jdbc.Driver
    #redis配置
    redis:
      host=127.0.0.1
      port=6379
      password=
mybatis:
  #导入映射文件
  mapper-locations: classpath:/mapper/**/*.xml

#rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default


