server:
  port: 8080
project:
  auther: czh
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Springboot_Vue?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: biefanglajiao
#    password: 020116zh
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #如果需要在一个xml文件中执行多个sql语句 需要在url后面添加：&allowMultiQueries=true
##    #redis配置
  #服务器配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/springboot_vue?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  #本地连服务器
  datasource:
    url: jdbc:mysql://120.78.134.171:3306/springboot_vue?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: springboot_vue
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #如果需要在一个xml文件中执行多个sql语句 需要在url后面添加：&allowMultiQueries=true
    #redis配置
    redis:
      host=127.0.0.1
      port=6379
      password=
mybatis:
  #导入映射文件
  mapper-locations: classpath:/mapper/**/*.xml

#rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: default


