server:
  port: 8080
project:
  auther: czh
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Springboot_Vue?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: biefanglajiao
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver